sudo: required
services:
    - docker

before_install:
    - docker build -t kof900/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true kof900/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-524015885515"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY